on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode BASEURL
        run: echo API_BASE_URL=TEST > ./local.properties
#        env:
#          API_BASE_URL: ${{ secrets.API_BASE_URL }}
#        run: echo API_BASE_URL=$API_BASE_URL > ./local.properties
      - name: Unit tests
        run: ./gradlew test --stacktrace

  android_tests:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode BASEURL
        run: echo API_BASE_URL=TEST > ./local.properties
#        env:
#          API_BASE_URL: ${{ secrets.API_BASE_URL }}
#        run: echo API_BASE_URL=$API_BASE_URL > ./local.properties
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-build: 7425822
          script: ./gradlew connectedCheck --stacktrace
