name: Android tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode BASEURL
        run: echo API_BASE_URL=TEST > ./local.properties
      - name: Config Luffy API
        env:
          Y: ${{secrets.API_BASE_URL}}
        run: echo -e "API_BASE_URL=$Y \n" >> ./local.properties
      - name: Config Avatar API
        env:
          X : ${{secrets.AVATAR_API}}
        run: echo -e "AVATAR_API=$X \n" >> ./local.properties
      - name: Config RabbitMQ
        env:
          A : ${{secrets.RABBITMQ_HOST}}
          B : ${{secrets.RABBITMQ_PORT}}
          C : ${{secrets.RABBIT_USER_NAME}}
          D : ${{secrets.RABBIT_USER_PASSWORD}}
        run: echo -e "RABBITMQ_HOST=$A\nRABBITMQ_PORT=$B\nRABBIT_USER_NAME=$C\nRABBIT_USER_PASSWORD=$D" >> ./local.properties
      - name: Unit tests
        run: ./gradlew test --stacktrace

  android_tests:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Config Luffy API
        env:
          Y: ${{secrets.API_BASE_URL}}
        run: echo -e "API_BASE_URL=$Y \n" >> ./local.properties
      - name: Config Avatar API
        env:
          X : ${{secrets.AVATAR_API}}
        run: echo -e "AVATAR_API=$X \n" >> ./local.properties
      - name: Config RabbitMQ
        env:
          A : ${{secrets.RABBITMQ_HOST}}
          B : ${{secrets.RABBITMQ_PORT}}
          C : ${{secrets.RABBIT_USER_NAME}}
          D : ${{secrets.RABBIT_USER_PASSWORD}}
        run: echo -e "RABBITMQ_HOST=$A\nRABBITMQ_PORT=$B\nRABBIT_USER_NAME=$C\nRABBIT_USER_PASSWORD=$D" >> ./local.properties
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-build: 7425822
          script: ./gradlew connectedCheck --stacktrace
