name: Android release signed artifact

on:
  push:
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Config Luffy API
        env:
          Y: ${{secrets.API_BASE_URL}}
        run: echo -e "API_BASE_URL=$Y \n" >> ./local.properties
      - name: Config Avatar API
        env:
          X : ${{secrets.AVATAR_API}}
        run: echo -e "AVATAR_API=$X \n" >> ./local.properties
      - name: Config RabbitMQ
        env:
          A : ${{secrets.RABBITMQ_HOST}}
          B : ${{secrets.RABBITMQ_PORT}}
          C : ${{secrets.RABBIT_USER_NAME}}
          D : ${{secrets.RABBIT_USER_PASSWORD}}
        run: echo -e "RABBITMQ_HOST=$A\nRABBITMQ_PORT=$B\nRABBIT_USER_NAME=$C\nRABBIT_USER_PASSWORD=$D" >> ./local.properties
      - name: Build Release Artifact
        run: ./gradlew app:assembleRelease --stacktrace
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Release Artifacts
          path: app/build/outputs/apk/release/*.apk
      - name: Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
